### ISSUE TITLE
An strange behavior when running anycable-go (systemd restarts) 

### ISSUE THREAD

**Issue by GabrielMalakias** [anycable/anycable-go#10]
I've just published my system but sometimes systemd restarts this server throwing this error:

Sep 13 03:08:29 debian-yggdrasil bash[5523]: Broadcast to stream sensor_1: {"user":"external","message":"22.97","sid":98016}
Sep 13 03:08:29 debian-yggdrasil bash[5523]: panic: send on closed channel
Sep 13 03:08:29 debian-yggdrasil bash[5523]: goroutine 8 [running]:
Sep 13 03:08:29 debian-yggdrasil bash[5523]: main.(*Hub).run(0xa99d40)
Sep 13 03:08:29 debian-yggdrasil bash[5523]: #011/Users/palkan/lib/go/src/github.com/anycable/anycable-go/hub.go:107 +0x9f8
Sep 13 03:08:29 debian-yggdrasil bash[5523]: created by main.main
Sep 13 03:08:29 debian-yggdrasil bash[5523]: #011/Users/palkan/lib/go/src/github.com/anycable/anycable-go/server.go:176 +0x281
Sep 13 03:08:29 debian-yggdrasil systemd[1]: anycable-go.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Sep 13 03:08:29 debian-yggdrasil systemd[1]: anycable-go.service: Unit entered failed state.
Sep 13 03:08:29 debian-yggdrasil systemd[1]: anycable-go.service: Failed with result 'exit-code'.
Sep 13 03:08:39 debian-yggdrasil systemd[1]: anycable-go.service: Service hold-off time over, scheduling restart.

**Comment by GabrielMalakias** [comment]
Thank you!

**Comment by palkan** [comment]
Note: I haven't tried it in production yet; but I've added a test for this small change, everything looks good)

**Comment by palkan** [comment]
Binaries uploaded, see Downloads page

**Comment by GabrielMalakias** [comment]
Ok.. That's fine, I'm testing it in a personal project, so the whole project is in beta. ;)
